In [3]:
import torch

x = torch.arange(12)

print(x)

print(x.numel())  # 返回一个张量中元素的总数


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
12


In [8]:
X = x.reshape(3,4)
print(X)
shape = X.T.shape
print(shape)

x = x.reshape(shape)
print(x)

Y = torch.concatenate([x,x], dim=0)
print(Y)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [2]:
help(torch.Tensor.numel)


Help on method_descriptor:

numel(...)
    numel() -> int
    
    See :func:`torch.numel`



In [14]:
import numpy as np
import torch

x = torch.arange(12).reshape(3,4)
y = np.ndarray(shape=(3,4))

print(type(x))      # <class 'torch.Tensor'>
print(type(y))      # <class 'numpy.ndarray'>

x_ = x.numpy()
y_ = torch.tensor(y)  # 涉及到数据拷贝
y__ = torch.from_numpy(y)  # 不涉及数据拷贝，更快、更节省内存

print(type(x_))     # <class 'numpy.ndarray'>
print(type(y_))     # <class 'torch.Tensor'>
print(type(y__))    # <class 'torch.Tensor'>


<class 'torch.Tensor'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
132345610180176
132347164345824
132347164359984


In [22]:
a = torch.arange(12)
b = a.reshape(3,4)
b[:] = 100
print(a)
print(a._is_view())
print(b._is_view())


tensor([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])
False
True


In [21]:
import torch
import torch.nn as nn


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 5)
    
    def forward(self, x):
        x = self.conv1(x)
        return x



SyntaxError: invalid syntax (1767136994.py, line 1)