In [12]:
import torch
import numpy as np

In [13]:
x = torch.arange(12,dtype=torch.uint8)
y = torch.ones((3,4))
print(x)
print(y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=torch.uint8)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [14]:
print(x.shape)
print(y.shape)

torch.Size([12])
torch.Size([3, 4])


In [15]:
print(x.numel())  # 元素个数
print(y.numel())  # 元素个数

12
12


In [16]:
x = x.reshape(1,12)  # 不改变元素数量和元素值，改变形状
print(x)
print(x.shape)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]], dtype=torch.uint8)
torch.Size([1, 12])


In [19]:
z = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32,requires_grad=True)
print(z)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [20]:
print(torch.exp(z))

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]], grad_fn=<ExpBackward0>)


In [24]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.arange(12,dtype=torch.float32).reshape((3,4))

print(torch.hstack((X,Y)),torch.vstack((X,Y)))
# 个人理解，dim就是修改哪个维度的值，保持其他维度不变
print(torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1))

tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]]) tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]])


In [25]:
X.sum()

tensor(66.)

In [27]:
# 广播机制，维度一样
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a+b  # a->3*2 b->3*2

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [29]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [32]:
Xnp = X.numpy()
XTorch = torch.tensor(Xnp)
print(Xnp)
print(XTorch)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [33]:
a = torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)