# <a id='toc1_'></a>[Numpy](#toc0_)

[NumPy user guide](https://numpy.org/doc/stable/user/index.html)

**Table of contents**<a id='toc0_'></a>    
- [Numpy](#toc1_)    
  - [01 - Getting started](#toc1_1_)    
    - [What is NumPy?](#toc1_1_1_)    
    - [Why is NumPy Fast?](#toc1_1_2_)    
    - [NumPy quickstart](#toc1_1_3_)    
  - [02 - Fundamentals and usage](#toc1_2_)    
  - [03 - Advanced usage and interoperability](#toc1_3_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [1]:
import numpy as np

## <a id='toc1_1_'></a>[01 - Getting started](#toc0_)

### <a id='toc1_1_1_'></a>[What is NumPy?](#toc0_)

For **fast operations** on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.



At the core of the NumPy package, is the **ndarray** object.

Several important differences between NumPy arrays and the standard Python sequences
1. NumPy arrays have **a fixed size at creation**
2. The elements in a NumPy array are all required to be of the **same data type**
3. Operations are executed **more efficiently** and with less code

Element-by-element operations are the “default mode” when an ndarray is involved

Element-by-element operation is speedily executed by pre-compiled C code. 


### <a id='toc1_1_2_'></a>[Why is NumPy Fast?](#toc0_)

Vectorization describes the absence of any explicit looping, indexing

pre-compiled C code

Broadcasting is the term used to describe the **implicit element-by-element behavior of operations**

In NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast

a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays of with different shapes, provided that the **smaller array is “expandable” to the shape of the larger** in such a way that the resulting broadcast is unambiguous

In [2]:
a = [1,2,3,4]
b = [2,3,4,5]

np_a = np.array(a, dtype=np.uint8)
np_b = np.array(b, dtype=np.uint8)

np_a_t = np.reshape(np_a, (-1,1))

print(np_a_t)

print(np_a*np_b)  # 对应位置相乘

print(np_a_t*np_b)  # 广播 broadcast

print(repr(np_a_t))

[[1]
 [2]
 [3]
 [4]]
[ 2  6 12 20]
[[ 2  3  4  5]
 [ 4  6  8 10]
 [ 6  9 12 15]
 [ 8 12 16 20]]
array([[1],
       [2],
       [3],
       [4]], dtype=uint8)


### <a id='toc1_1_3_'></a>[NumPy quickstart](#toc0_)

apply common functions to n-dimensional arrays (without using for-loops), or if you want to understand axis and shape properties for n-dimensional arrays

Understand the difference between one-, two- and n-dimensional arrays in NumPy;

Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops;

Understand axis and shape properties for n-dimensional arrays.

**The Basics**

NumPy’s main object is the homogeneous multidimensional array (all of the same type)

indexed by a tuple of non-negative integers

In NumPy dimensions are called **axes**(axis)

NumPy’s array class is called ndarray. It is also known by the alias array.

Note that numpy.array is not the same as the Standard Python Library class array.array(only handles one-dimensional arrays and offers less functionality)


**attributes of an ndarray object**
1. ndarray.**ndim** - the number of axes (dimensions) of the array.
2. ndarray.**shape** - the dimensions of the array. This is a tuple of integers indicating the size of the array
3. ndarray.**size** - the total number of elements of the array. This is equal to the product of the elements of shape
4. ndarray.**dtype** - an object describing the type of the elements in the array(can create or specify dtype’s using standard Python types)
5. ndarray.**itemsize** - the size in bytes of each element of the array (float64 has itemsize 8 (=64/8))
6. ndarray.**data** - the buffer containing the actual elements of the array.

当使用 np.ndarray 来创建数组时，NumPy 并不会自动初始化数组中的元素，这意味着数组中的元素是随机的，实际上是未初始化的。

In [3]:
a = np.ndarray(shape=(4,3,2), dtype=np.int16,)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

b = np.ndarray(shape=(1,2), dtype=str)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)  # <U0 : This indicates a Unicode string of unspecified length, a common way NumPy represents string data
print(b.itemsize)
print(b.data)


# == 运算符在这里被 NumPy 重载
print(b.dtype == str)  # True
print(b.dtype == np.str_)  # True
print(b.dtype == np.unicode_)  # True
print(np.str_ == str)  # False
print(b.dtype == np.dtypes.StrDType)  # False
print(type(b.dtype))  # <class 'numpy.dtypes.StrDType'>
print(type(b.dtype) == np.dtypes.StrDType)  # True
print(isinstance(b.dtype, str))  # False
print(isinstance(b.dtype, np.dtypes.StrDType))  # True


print(b.dtype.char == 'U')  # True  # # 检查是否是 Unicode 字符串类型

3
(4, 3, 2)
24
int16
2
2
(1, 2)
2
<U0
0
True
True
True
False
False
<class 'numpy.dtypes.StrDType'>
True
False
True
True


## <a id='toc1_2_'></a>[02 - Fundamentals and usage](#toc0_)

## <a id='toc1_3_'></a>[03 - Advanced usage and interoperability](#toc0_)