# <a id='toc1_'></a>[Numpy](#toc0_)

[NumPy user guide](https://numpy.org/doc/stable/user/index.html)

**Table of contents**<a id='toc0_'></a>    
- [Numpy](#toc1_)    
  - [01 - Getting started](#toc1_1_)    
    - [What is NumPy?](#toc1_1_1_)    
    - [Why is NumPy Fast?](#toc1_1_2_)    
    - [NumPy quickstart](#toc1_1_3_)    
    - [Array Creation](#toc1_1_4_)    
    - [Printing Arrays](#toc1_1_5_)    
    - [Basic Operations](#toc1_1_6_)    
    - [Universal Functions](#toc1_1_7_)    
    - [Indexing, Slicing and Iterating](#toc1_1_8_)    
    - [Shape Manipulation](#toc1_1_9_)    
    - [Stacking together different arrays](#toc1_1_10_)    
    - [Splitting one array into several smaller ones](#toc1_1_11_)    
    - [Copies and Views](#toc1_1_12_)    
      - [No Copy at All](#toc1_1_12_1_)    
      - [View or Shallow Copy](#toc1_1_12_2_)    
      - [Deep Copy](#toc1_1_12_3_)    
    - [Functions and Methods Overview](#toc1_1_13_)    
    - [Less Basic](#toc1_1_14_)    
  - [02 - Fundamentals and usage](#toc1_2_)    
  - [03 - Advanced usage and interoperability](#toc1_3_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

In [138]:
import numpy as np


## <a id='toc1_1_'></a>[01 - Getting started](#toc0_)

### <a id='toc1_1_1_'></a>[What is NumPy?](#toc0_)

For **fast operations** on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.



At the core of the NumPy package, is the **ndarray** object.

Several important differences between NumPy arrays and the standard Python sequences
1. NumPy arrays have **a fixed size at creation**
2. The elements in a NumPy array are all required to be of the **same data type**
3. Operations are executed **more efficiently** and with less code

Element-by-element operations are the “default mode” when an ndarray is involved

Element-by-element operation is speedily executed by pre-compiled C code. 


### <a id='toc1_1_2_'></a>[Why is NumPy Fast?](#toc0_)

Vectorization describes the absence of any explicit looping, indexing

pre-compiled C code

Broadcasting is the term used to describe the **implicit element-by-element behavior of operations**

In NumPy all operations, not just arithmetic operations, but logical, bit-wise, functional, etc., behave in this implicit element-by-element fashion, i.e., they broadcast

a and b could be multidimensional arrays of the same shape, or a scalar and an array, or even two arrays of with different shapes, provided that the **smaller array is “expandable” to the shape of the larger** in such a way that the resulting broadcast is unambiguous

In [139]:
a = [1,2,3,4]
b = [2,3,4,5]

np_a = np.array(a, dtype=np.uint8)
np_b = np.array(b, dtype=np.uint8)

np_a_t = np.reshape(np_a, (-1,1))

print(np_a_t)

print(np_a*np_b)  # 对应位置相乘

print(np_a_t*np_b)  # 广播 broadcast

print(repr(np_a_t))


[[1]
 [2]
 [3]
 [4]]
[ 2  6 12 20]
[[ 2  3  4  5]
 [ 4  6  8 10]
 [ 6  9 12 15]
 [ 8 12 16 20]]
array([[1],
       [2],
       [3],
       [4]], dtype=uint8)


### <a id='toc1_1_3_'></a>[NumPy quickstart](#toc0_)

apply common functions to n-dimensional arrays (without using for-loops), or if you want to understand axis and shape properties for n-dimensional arrays

Understand the difference between one-, two- and n-dimensional arrays in NumPy;

Understand how to apply some linear algebra operations to n-dimensional arrays without using for-loops;

Understand axis and shape properties for n-dimensional arrays.

**The Basics**

NumPy’s main object is the homogeneous multidimensional array (all of the same type)

indexed by a tuple of non-negative integers

In NumPy dimensions are called **axes**(axis)

NumPy’s array class is called ndarray. It is also known by the alias array.

Note that numpy.array is not the same as the Standard Python Library class array.array(only handles one-dimensional arrays and offers less functionality)


**attributes of an ndarray object**
1. ndarray.**ndim** - the number of axes (dimensions) of the array.
2. ndarray.**shape** - the dimensions of the array. This is a tuple of integers indicating the size of the array
3. ndarray.**size** - the total number of elements of the array. This is equal to the product of the elements of shape
4. ndarray.**dtype** - an object describing the type of the elements in the array(can create or specify dtype’s using standard Python types)
5. ndarray.**itemsize** - the size in bytes of each element of the array (float64 has itemsize 8 (=64/8))
6. ndarray.**data** - the buffer containing the actual elements of the array.

当使用 np.ndarray 来创建数组时，NumPy 并不会自动初始化数组中的元素，这意味着数组中的元素是随机的，实际上是未初始化的。

In [140]:
a = np.ndarray(shape=(4,3,2), dtype=np.int16,)

print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

b = np.ndarray(shape=(1,2), dtype=str)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)  # <U0 : This indicates a Unicode string of unspecified length, a common way NumPy represents string data
print(b.itemsize)
print(b.data)


# == 运算符在这里被 NumPy 重载
print(b.dtype == str)  # True
print(b.dtype == np.str_)  # True
print(b.dtype == np.unicode_)  # True
print(np.str_ == str)  # False
print(b.dtype == np.dtypes.StrDType)  # False
print(type(b.dtype))  # <class 'numpy.dtypes.StrDType'>
print(type(b.dtype) == np.dtypes.StrDType)  # True
print(isinstance(b.dtype, str))  # False
print(isinstance(b.dtype, np.dtypes.StrDType))  # True


print(b.dtype.char == 'U')  # True  # # 检查是否是 Unicode 字符串类型


3
(4, 3, 2)
24
int16
2
2
(1, 2)
2
<U0
0
True
True
True
False
False
<class 'numpy.dtypes.StrDType'>
True
False
True
True


### <a id='toc1_1_4_'></a>[Array Creation](#toc0_)

In [141]:
a = np.array([1, 2, 3, 4])  # create an array from a regular Python list or tuple using the array function

b = np.array([(1.5, 2, 3), (4, 5, 6)])  # array transforms sequences of sequences into two-dimensional arrays

c = np.array([[1, 2], [3, 4]], dtype=complex)  # The type of the array can also be explicitly specified at creation time

d = np.zeros((3, 4))  # zeros creates an array full of zeros

e = np.ones((2, 3, 4), dtype=np.int16)  # ones creates an array full of ones

f = np.empty((2, 3))  # empty creates an array whose initial content is random and depends on the state of the memory

g = np.arange(start=1, stop=10, step=3)  # [1 4 7]  # create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range

h = np.linspace(start=1, stop=10, num=4, endpoint=True, dtype=np.int16)  # [ 1  4  7 10]  # linspace that receives as an argument the number of elements that we want, instead of the step


### <a id='toc1_1_5_'></a>[Printing Arrays](#toc0_)

Layout
1. the last axis is printed from left to right,
2. the second-to-last is printed from top to bottom,
3. the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

个人理解就是 shape 的最后两位是按正常理解的二位数组打印的，以后的都是从上到下

If an array is too large to be printed, NumPy automatically **skips the central part of the array and only prints the corners**

To disable this behaviour and force NumPy to print the entire array, you can change the printing options using **set_printoptions**

In [142]:
layout = np.arange(0, 2*3*4*5).reshape((2,3,4,5))  # 4,5就是按正常理解的二位数组打印，然后3是从上到下，最后2从上到下

print(layout)


[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


In [143]:
big = np.arange(0,10000,dtype=np.uint8).reshape((100,100))
print(big)

# [[  0   1   2 ...  97  98  99]
#  [100 101 102 ... 197 198 199]
#  [200 201 202 ...  41  42  43]
#  ...
#  [228 229 230 ...  69  70  71]
#  [ 72  73  74 ... 169 170 171]
#  [172 173 174 ...  13  14  15]]


# try 
# import sys
# np.set_printoptions(threshold=sys.maxsize)


[[  0   1   2 ...  97  98  99]
 [100 101 102 ... 197 198 199]
 [200 201 202 ...  41  42  43]
 ...
 [228 229 230 ...  69  70  71]
 [ 72  73  74 ... 169 170 171]
 [172 173 174 ...  13  14  15]]


### <a id='toc1_1_6_'></a>[Basic Operations](#toc0_)

Arithmetic operators on arrays apply **elementwise**. 

**A new array is created** and filled with the result.

Some operations, such as **+= and *=**, **act in place to modify an existing array** rather than create a new one

Key:
1. **The product operator * operates elementwise in NumPy arrays**
2. **The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method**

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one
(a behavior known as upcasting) 向上转型


In [144]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
c = a - b
d = b**2
e = 10 * np.sin(a)
f = np.sin(45/180*np.pi)/(np.sqrt(2)/2)
g = np.sqrt(d) - b
h = a < 35
print(a,b,c,d,e,f,g,h, sep="\n")

a += b
print(a)


[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
0.9999999999999999
[0. 0. 0. 0.]
[ True  True False False]
[20 31 42 53]


In [145]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

print(A*B)
print(A@B)
print(np.dot(A,B))
print(A.dot(B))


[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


Many unary operations(一元运算), such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

By default, **these operations apply to the array** as though it were a list of numbers, regardless of its shape. However

by specifying the axis parameter you can apply an operation along the specified axis of an array(axis对应shape)

个人理解 :
对于 inputMat shape=(a,b,c,d)
对应 axis 编号为 (0,1,2,3)
如果 传入axis=1， 对应压缩 b-axis，输出shape=(a,c,d)
其中(a1,c1,d1)位置的元素 = max(inputMat(a1,:,c1,d1))



In [146]:
mat = np.arange(start=0, stop=2*3*4*5, dtype=np.uint16).reshape((2,3,4,5))

print(mat)

print("mat.max(), mat.min(), mat.mean(), mat.sum()", mat.max(), mat.min(), mat.mean(), mat.sum())

a = mat.max(axis=0)
b = mat.max(axis=1)
c = mat.max(axis=2)
d = mat.max(axis=3)

print("mat.max(axis=0)", a.shape, a, sep="\n")
print("mat.max(axis=1)", b.shape, b, sep="\n")
print("mat.max(axis=2)", c.shape, c, sep="\n")
print("mat.max(axis=3)", d.shape, d, sep="\n")


[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]
mat.max(), mat.min(), mat.mean(), mat.sum() 119 0 59.5 7140
mat.max(axis=0)
(3, 4, 5)
[[[ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]
  [ 75  76  77  78  79]]

 [[ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]]]
mat.m

### <a id='toc1_1_7_'></a>[Universal Functions](#toc0_)

NumPy provides familiar mathematical functions such as sin, cos, and exp. 

In NumPy, these are called “universal functions” (ufunc). 

Within NumPy, these functions operate elementwise on an array, producing an array as output.

[Universal Functions](https://numpy.org/doc/stable/user/quickstart.html#universal-functions)

```text
all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef,
cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min,
minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where
```


### <a id='toc1_1_8_'></a>[Indexing, Slicing and Iterating](#toc0_)

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

**Multidimensional** arrays can have one index per axis. These indices are given in **a tuple separated by commas:**

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes.

NumPy also allows you to write this using dots as b[i, ...].
1. x[1, 2, ...] is equivalent to x[1, 2, :, :, :],
2. x[..., 3] to x[:, :, :, :, 3] 
3. x[4, ..., 5, :] to x[4, :, :, 5, :].

**flat** : if one wants to perform an operation **on each element in the array**, one can use the **flat attribute** which is an iterator over all the elements of the array:


In [147]:
def helpFun(x,y):
    return 10*x+y

mat = np.fromfunction(function=helpFun,shape=(5,4),dtype=int)

print(mat)

print(mat[...,-1])

mat = np.arange(start=0, stop=2*3*4*5, dtype=np.uint8).reshape((2,3,4,5))

print(mat)

print(mat[...,-1])

from collections.abc import Iterable, Iterator
print(isinstance(mat.flat, Iterable))  # True
print(isinstance(mat.flat, Iterator))  # True

for element in mat.flat:
    print(element, end=",")


[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
[ 3 13 23 33 43]
[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]
[[[  4   9  14  19]
  [ 24  29  34  39]
  [ 44  49  54  59]]

 [[ 64  69  74  79]
  [ 84  89  94  99]
  [104 109 114 119]]]
True
True
0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,

In [180]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print((a<8) & (a>3))
print(a[a < 8])


b = np.nonzero(a<8)
print(b)
coordinates= list(zip(b[0], b[1]))
print(coordinates)


[[False False False  True]
 [ True  True  True False]
 [False False False False]]
[1 2 3 4 5 6 7]
(array([0, 0, 0, 0, 1, 1, 1]), array([0, 1, 2, 3, 0, 1, 2]))
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2)]


### <a id='toc1_1_9_'></a>[Shape Manipulation](#toc0_)

An array has a shape given by the number of elements along each axis

The shape of an array can be changed with various commands.

Note that the following three commands all return a modified array, but do not change the original array:
1. ravel  - The order of the elements in the array resulting from ravel is normally “C-style”
2. reshape
3. T - 形状完全对调

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:
1. reshape - 不改变原mat - 形状不匹配会抛出错误
2. resize - 改变原来mat - 总大小可以不同于原始数组，refcheck=False



In [168]:
mat = np.ndarray(shape=(2,3,4))
print(mat)
mat1 = mat.ravel()  # returns the array, flattened
mat2 = mat.T
mat3 = mat.reshape((-1))
mat.resize((4,2,4), refcheck=False)

print(mat.shape, mat1.shape, mat2.shape, mat3.shape)
print(mat)

mat = np.ndarray(shape=(2,3,4,5))
mat4 = mat.T
print(mat.shape, mat4.shape)


a = np.array([1, 2, 3, 4, 5, 6])
print(a.shape)
a2 = a[np.newaxis, :]
print(a2.shape)

a3 = np.expand_dims(a2, axis=2)
print(a3.shape)


[[[5. 9. 1. 9.]
  [3. 4. 3. 7.]
  [3. 4. 1. 4.]]

 [[8. 4. 5. 0.]
  [7. 5. 2. 2.]
  [7. 2. 4. 9.]]]
(4, 2, 4) (24,) (4, 3, 2) (24,)
[[[5. 9. 1. 9.]
  [3. 4. 3. 7.]]

 [[3. 4. 1. 4.]
  [8. 4. 5. 0.]]

 [[7. 5. 2. 2.]
  [7. 2. 4. 9.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4, 5) (5, 4, 3, 2)
(6,)
(1, 6)
(1, 6, 1)


### <a id='toc1_1_10_'></a>[Stacking together different arrays](#toc0_)

Several arrays can be stacked together along different axes:
1. vstack - 改变第0轴大小 - np.concatenate((a,b),axis=0)
2. hstack - 改变第1轴大小 - np.concatenate((a,b),axis=1)
3. [concatenate](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate)
4. row_stack is equivalent to vstack for any input arrays. In fact, row_stack is an alias for vstack
5. r_ and c_ are useful for creating arrays by stacking numbers along one axis
6. column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays



In [164]:
rg = np.random.default_rng(1)  # create instance of default random number generator

a = np.floor(10 * rg.random((2, 2, 3)))
b = np.floor(10 * rg.random((2, 2, 3)))

print(a)
print(b)
print("--------------")
print(np.vstack((a,b)))
print(np.hstack((a,b)))

print(np.concatenate((a,b),axis=0) == np.vstack((a,b)))
print(np.concatenate((a,b),axis=1) == np.hstack((a,b)))

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))


[[[5. 9. 1.]
  [9. 3. 4.]]

 [[8. 4. 5.]
  [0. 7. 5.]]]
[[[3. 7. 3.]
  [4. 1. 4.]]

 [[2. 2. 7.]
  [2. 4. 9.]]]
--------------
[[[5. 9. 1.]
  [9. 3. 4.]]

 [[8. 4. 5.]
  [0. 7. 5.]]

 [[3. 7. 3.]
  [4. 1. 4.]]

 [[2. 2. 7.]
  [2. 4. 9.]]]
[[[5. 9. 1.]
  [9. 3. 4.]
  [3. 7. 3.]
  [4. 1. 4.]]

 [[8. 4. 5.]
  [0. 7. 5.]
  [2. 2. 7.]
  [2. 4. 9.]]]
[[[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]
  [ True  True  True]]]
[1 2 3 4 5 6 7 8]


### <a id='toc1_1_11_'></a>[Splitting one array into several smaller ones](#toc0_)

Using hsplit, you can split an array along its horizontal axis
1. either by specifying the number of equally shaped arrays to return
2. or by specifying the columns after which the division should occur



In [150]:
a = np.floor(10 * rg.random((2, 12)))
arrayList1 = np.hsplit(a, 4)
arrayList2 = np.vsplit(a, 2)


print(a)
print(arrayList1)
print(arrayList2)


[[9. 7. 5. 2. 1. 9. 5. 1. 6. 7. 6. 9.]
 [0. 5. 4. 0. 6. 8. 5. 2. 8. 5. 5. 7.]]
[array([[9., 7., 5.],
       [0., 5., 4.]]), array([[2., 1., 9.],
       [0., 6., 8.]]), array([[5., 1., 6.],
       [5., 2., 8.]]), array([[7., 6., 9.],
       [5., 5., 7.]])]
[array([[9., 7., 5., 2., 1., 9., 5., 1., 6., 7., 6., 9.]]), array([[0., 5., 4., 0., 6., 8., 5., 2., 8., 5., 5., 7.]])]


### <a id='toc1_1_12_'></a>[Copies and Views](#toc0_)

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners.

浅拷贝与深拷贝
1. 浅拷贝（Shallow Copy）
   1. 创建一个新对象，但是不会创建原有对象中的子对象的副本。这意味着，如果原有对象中包含了对其他对象的引用，那么浅拷贝出的新对象将使用对这些子对象的同样引用。
   2. 如果原对象或其任何子对象是可变的，那么无论是在新对象还是原对象中对这些可变子对象的任何改动都会互相影响。
2. 深拷贝（Deep Copy）
   1. 深拷贝创建一个新对象，同时递归地复制原有对象中的所有子对象。
   2. 深拷贝出的新对象和原有对象没有任何引用上的联系。因此，修改新对象不会影响原对象，反之亦然。


#### <a id='toc1_1_12_1_'></a>[No Copy at All](#toc0_)

Simple assignments make no copy of objects or their data.

Function calls make no copy

In [153]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            # no new object is created
print(b is a)    # True

def f(x):
    print(id(x))

print(id(a))
f(a)


True
123965919067856
123965919067856


#### <a id='toc1_1_12_2_'></a>[View or Shallow Copy](#toc0_)

Different array objects can share the same data. 

**The view method creates a new array object that looks at the same data.**

Slicing an array returns a view of it:

In [159]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

c = a.view()
print(c.base is a)  # True

c = c.reshape((2,6))
print(a.shape)  # a's shape doesn't change

print(c)

c[1,1] = 100

print(c)
print(c.base)
print(a)


True
(3, 4)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[  0   1   2   3   4   5]
 [  6 100   8   9  10  11]]
[[  0   1   2   3]
 [  4   5   6 100]
 [  8   9  10  11]]
[[  0   1   2   3]
 [  4   5   6 100]
 [  8   9  10  11]]


In [162]:
viewA = a[:,1:3]  # view of a
viewA[:] = 10  # Note the difference between s = 10 and s[:] = 10
print(a)


[[  0  10  10   3]
 [  4  10  10 100]
 [  8  10  10  11]]


#### <a id='toc1_1_12_3_'></a>[Deep Copy](#toc0_)

The copy method makes a complete copy of the array and its data.

doesn't share anything

In [163]:
d = a.copy()  # a new array object with new data is created
d is a


False

### Random


In [184]:
rng = np.random.default_rng()  # the simplest way to generate random numbers
print(rng.random(3))
print(rng.random((3, 2)))
print(rng.integers(5, size=(2, 4)) )


[0.72415084 0.8733271  0.2435794 ]
[[0.07948038 0.62585371]
 [0.04313009 0.18655248]
 [0.38454024 0.83180135]]
[[0 0 1 2]
 [0 2 3 0]]


### Unique

find the unique elements in an array easily with np.unique

In [187]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(np.unique(a))

unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)


[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]
[3 2 2 2 1 1 1 1 1 1]


In [188]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [189]:
unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
np.unique(ar=a_2d, return_index=True, return_counts=True)


(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1]))

### <a id='toc1_1_13_'></a>[Functions and Methods Overview](#toc0_)

Array Creation - 
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like

Conversions - 
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

Manipulations - 
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

Questions - 
all, any, nonzero, where

Ordering - 
argmax, argmin, argsort, max, min, ptp, searchsorted, sort

Operations - 
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

Basic Statistics - 
cov, mean, std, var

Basic Linear Algebra - 
cross, dot, outer, linalg.svd, vdot

### <a id='toc1_1_14_'></a>[Less Basic](#toc0_)


## <a id='toc1_2_'></a>[02 - Fundamentals and usage](#toc0_)

## <a id='toc1_3_'></a>[03 - Advanced usage and interoperability](#toc0_)